on:
  push:
    branches:
      - main

name: Release

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}

  publish:
    needs: [release-please]
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    if: ${{ needs.release-please.outputs.release_created }}
